version: "1.00"

services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - path: ./.env
        required: true
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    hostname: project1_db
    container_name: project1-db
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - path: ./.env
        required: true
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
volumes:
  web-django:
  web-static: